import { SpaService } from '@/lib/types';

const MASSAGE_IMAGE = 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1000&auto=format&fit=crop';
const BODY_IMAGE = 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=1000&auto=format&fit=crop';
const FACIAL_IMAGE = '/media/skincare_treatment_1782918671588.jpg';
const FACIAL_IMAGE_ALT = 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=1000&auto=format&fit=crop';
const ADVANCED_IMAGE = 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?q=80&w=1000&auto=format&fit=crop';

const askForPrice = {
  price: 'Ask for price',
  priceCents: null as number | null,
};

export const SPA_SERVICES: SpaService[] = [
  {
    id: '1',
    name: 'Relaxing Massage',
    category: 'Massages',
    image: MASSAGE_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Muscle tension relief', 'Stress reduction', 'Improved circulation', 'Overall sense of well-being'],
    description: 'A gentle, slow-paced massage with fluid strokes to relax body and mind, ideal for releasing accumulated stress and restoring calm.',
  },
  {
    id: '2',
    name: 'Deep Tissue Massage',
    category: 'Massages',
    image: MASSAGE_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Release of muscle knots', 'Relief from muscle pain', 'Greater mobility', 'Release of tense areas'],
    description: 'Moderate to deep pressure technique focused on knots, muscle tension, and tight areas in the back, neck, and shoulders.',
  },
  {
    id: '3',
    name: 'Relaxation Massage',
    category: 'Massages',
    image: MASSAGE_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Deep relaxation', 'Nervous system balance', 'Physical rest', 'Emotional well-being'],
    description: 'A full sensory relaxation experience with harmonious movements that promote physical and mental rest.',
  },
  {
    id: '4',
    name: 'Body Contouring Massage',
    category: 'Massages',
    image: BODY_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Local metabolism stimulation', 'Body sculpting', 'Reduced fluid retention', 'Firmer skin'],
    description: 'Medium to high-intensity massage designed to sculpt the silhouette, activate circulation, and support non-invasive body contouring.',
  },
  {
    id: '5',
    name: 'Lymphatic Drainage Massage',
    category: 'Massages',
    image: BODY_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Toxin elimination', 'Reduced inflammation', 'Improved lymphatic circulation', 'Light, refreshed feeling'],
    description: 'Gentle, rhythmic manual technique that stimulates the lymphatic system to help eliminate fluids and accumulated toxins.',
  },
  {
    id: '6',
    name: 'Facial Yoga Massage',
    category: 'Massages',
    image: FACIAL_IMAGE_ALT,
    duration: '45 minutes',
    ...askForPrice,
    benefits: ['Natural facial toning', 'Non-surgical lifting effect', 'Improved facial contour', 'Relaxed expression'],
    description: 'Facial massage routine inspired by facial yoga techniques to tone muscles, redefine the jawline, and enhance radiance.',
  },
  {
    id: '7',
    name: 'Post-Operative Lymphatic Drainage',
    category: 'Massages',
    image: BODY_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Reduced swelling', 'Post-surgical recovery support', 'Improved healing', 'Relief from inflammation'],
    description: 'Specialized manual lymphatic drainage protocol to support recovery after surgical procedures, with safe, personalized technique.',
  },
  {
    id: '8',
    name: 'Wood Therapy',
    category: 'Massages',
    image: BODY_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Body sculpting', 'Circulatory activation', 'Cellulite reduction', 'Tissue toning'],
    description: 'Body treatment using wooden instruments that combines massage and sculpting to shape, tone, and improve skin appearance.',
  },
  {
    id: '9',
    name: 'Basic Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE,
    duration: '45 minutes',
    ...askForPrice,
    benefits: ['Surface cleansing', 'Fresh, balanced skin', 'Impurity removal', 'Daily skin preparation'],
    description: 'Essential facial cleansing to keep skin clean, fresh, and balanced. Ideal for regular maintenance.',
  },
  {
    id: '10',
    name: 'Deep Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE,
    duration: '75 minutes',
    ...askForPrice,
    benefits: ['Impurity extraction', 'Purified pores', 'Cellular renewal', 'Smoother, more even skin'],
    description: 'Complete facial hygiene protocol with exfoliation, steam, and extraction to deeply renew the skin.',
  },
  {
    id: '11',
    name: 'Hydrating Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE_ALT,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Intense hydration', 'Skin barrier restoration', 'Immediate softness', 'Comfortable, luminous skin'],
    description: 'Facial treatment focused on restoring hydration levels with nourishing actives and restorative masks.',
  },
  {
    id: '12',
    name: 'Acne-Prone Skin Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE,
    duration: '75 minutes',
    ...askForPrice,
    benefits: ['Sebum control', 'Antibacterial action', 'Unclogged pores', 'Improvement of active breakouts'],
    description: 'Facial cleansing designed for acne-prone skin, focused on purification, balance, and calming the skin.',
  },
  {
    id: '13',
    name: 'Hyperpigmentation Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE_ALT,
    duration: '75 minutes',
    ...askForPrice,
    benefits: ['Even skin tone', 'Reduced dark spots', 'More uniform complexion', 'Renewed radiance'],
    description: 'Facial treatment aimed at fading dark spots and evening skin tone with professional depigmenting actives.',
  },
  {
    id: '14',
    name: 'Anti-Aging Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE,
    duration: '75 minutes',
    ...askForPrice,
    benefits: ['Collagen stimulation', 'Improved firmness', 'Softened fine lines', 'More youthful appearance'],
    description: 'Anti-aging protocol combining cleansing, regenerating actives, and manual techniques to revitalize and firm the skin.',
  },
  {
    id: '15',
    name: 'Hydrafacial',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE_ALT,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Technology-powered cleansing', 'Deep hydration', 'Instant glow', 'No downtime'],
    description: 'Facial treatment with hydrodermabrasion technology that cleanses, exfoliates, extracts, and hydrates in a single session.',
  },
  {
    id: '16',
    name: 'Oxygenating Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Cellular oxygenation', 'Revitalized skin', 'Rested appearance', 'Enhanced skin vitality'],
    description: 'Facial that delivers oxygen and nutrients to the skin to restore energy, freshness, and a healthier appearance.',
  },
  {
    id: '17',
    name: 'Premium Facial Cleansing',
    category: 'Facial Cleansing',
    image: FACIAL_IMAGE,
    duration: '90 minutes',
    ...askForPrice,
    benefits: ['Luxury experience', 'Personalized protocol', 'Visible results', 'Maximum comfort and care'],
    description: 'The studio\'s most complete facial experience: deep cleansing, premium actives, and a personalized ritual for outstanding results.',
  },
  {
    id: '18',
    name: 'Platelet-Rich Plasma',
    category: 'Advanced Treatments',
    image: ADVANCED_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Tissue regeneration', 'Collagen stimulation', 'Improved skin texture', 'Natural rejuvenation'],
    description: 'Advanced PRP treatment that uses growth factors from your own blood to stimulate skin regeneration and quality.',
  },
  {
    id: '19',
    name: 'Salmon PDRN',
    category: 'Advanced Treatments',
    image: ADVANCED_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Cellular repair', 'Deep hydration', 'Improved elasticity', 'More resilient skin'],
    description: 'Bio-stimulator with salmon polynucleotides that supports cellular repair, hydration, and skin regeneration.',
  },
  {
    id: '20',
    name: 'Exosomes',
    category: 'Advanced Treatments',
    image: ADVANCED_IMAGE,
    duration: '60 minutes',
    ...askForPrice,
    benefits: ['Advanced regeneration', 'Cellular communication', 'Next-generation anti-aging', 'Renewed, luminous skin'],
    description: 'Cutting-edge exosome treatment that enhances skin regeneration, improves skin quality, and delivers a rejuvenating effect.',
  },
  {
    id: '21',
    name: 'Wax Hair Removal',
    category: 'Waxing',
    image: BODY_IMAGE,
    duration: '45 minutes',
    ...askForPrice,
    benefits: ['Smooth, hair-free skin', 'Long-lasting results', 'Hygienic, precise application', 'Ideal for face and body'],
    description: 'Professional warm wax hair removal using high-quality wax for effective results, leaving skin smooth, cared for, and flawlessly finished.',
  },
  {
    id: '22',
    name: 'Eyebrow Design',
    category: 'Brows & Face',
    image: FACIAL_IMAGE_ALT,
    duration: '30 minutes',
    ...askForPrice,
    benefits: ['Symmetrical, harmonious brows', 'More defined face', 'Personalized design', 'Natural, elegant finish'],
    description: 'Professional eyebrow design tailored to your face shape, enhancing your gaze with precision shaping, hair removal, and finishing techniques.',
  },
  {
    id: '23',
    name: 'Brow Laminate',
    category: 'Brows & Face',
    image: FACIAL_IMAGE_ALT,
    duration: '45 minutes',
    ...askForPrice,
    benefits: ['Visually fuller brows', 'Groomed, styled effect', 'Enhanced definition', 'Long-lasting results'],
    description: 'Brow lamination treatment that smooths, sets, and directs brow hairs for a fuller, structured, polished look that lasts for weeks.',
  },
];

export const FAQ_ITEMS = [
  {
    question: 'What types of massages does Yoly Studio offer?',
    answer: 'We offer relaxing massage, deep tissue massage, relaxation massage, body contouring massage, lymphatic drainage, facial yoga massage, post-operative lymphatic drainage, and wood therapy, always tailored to your needs.',
  },
  {
    question: 'What facial cleansing treatments are available?',
    answer: 'We offer basic, deep, hydrating, acne-prone skin, hyperpigmentation, anti-aging, and premium facial cleansing, as well as Hydrafacial.',
  },
  {
    question: 'What advanced treatments do you perform?',
    answer: 'We apply premium protocols such as Platelet-Rich Plasma (PRP), Salmon PDRN, and Exosomes for skin regeneration and rejuvenation.',
  },
  {
    question: 'What care should I take before and after a facial treatment?',
    answer: 'Before your appointment, avoid prolonged direct sun exposure and do not use acids or abrasive at-home peels. After treatment, apply SPF 50+ sunscreen, keep your skin hydrated, and avoid heavy makeup for the first 24 hours.',
  },
  {
    question: 'Do you offer waxing and brow services?',
    answer: 'Yes. We provide wax hair removal, eyebrow design, and Brow Laminate using professional techniques tailored to each face.',
  },
  {
    question: 'How does the booking and cancellation process work?',
    answer: 'You can pre-book your appointment online by selecting the service, date, and time. Yoly will confirm your appointment personally by phone or WhatsApp. If you need to reschedule or cancel, please notify us at least 24 hours in advance.',
  },
];
